name: 'dbt_snowflake_airflow_etl_pipeline'
version: '1.0.0'
profile: 'dbt_snowflake_airflow_etl_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_snowflake_airflow_etl_pipeline:
    example:
      Staging:
        +materialized: view
      marts:
        +materialized: table
